### ISSUE TITLE
Cheat console disabling

### ISSUE THREAD

**Issue by Michael21107** [Rohit685/DynamicWeather#14]
having the plugin loaded disables the cheat console (`~`) no matter what the DW keys are set to

**Comment by Rohit685** [comment]
I fixed the issue in the patch branch. U can build and use.

**Comment by Michael21107** [comment]
@Rohit685 thanks but i don't know how to build 😭

**Comment by Michael21107** [comment]
@Rohit685 Hey, I managed to build the patch I believe and it seems like everything works now.
